{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "fluentd.fullname" . }}
  labels:
    {{- include "fluentd.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "fluentd.selectorLabels" . | nindent 6 }}
  ingress:
    - ports:
      - port: 24231
        protocol: TCP
      {{- if .Values.service.ports }}
      {{- range $port := .Values.service.ports }}
      - port: {{ $port.containerPort }}
        protocol: {{ $port.protocol }}
      {{- end }}
      {{- end }}
  {{- with .Values.networkPolicy }}
  egress:
    {{- toYaml .egress | nindent 4 }}
  {{- end }}
{{- end }}
