testFramework:
  enabled: true

logLevel: debug

dashboards:
  enabled: true
  deterministicUid: true

config:
  outputs: |
    [OUTPUT]
        name   stdout
        match  *

hotReload:
  enabled: true
