testFramework:
  enabled: true

logLevel: debug

extraVolumeMounts:
  - name: extra-volume
    mountPath: /extra-volume-path
  - name: another-extra-volume
    mountPath: /another-extra-volume-path

extraVolumes:
  - name: extra-volume
    emptyDir: {}
  - name: another-extra-volume
    emptyDir: {}

dashboards:
  enabled: true
  deterministicUid: true

config:
  outputs: |
    [OUTPUT]
        name   stdout
        match  *

hotReload:
  enabled: true
  extraWatchVolumes:
    - extra-volume
    - another-extra-volume
