{{- if .Values.fluentbit.enable -}}
{{- if .Values.fluentbit.output.prometheusMetricsExporter -}}
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: prometheus-exporter
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  match: {{ .Values.fluentbit.output.prometheusMetricsExporter.match }}
  prometheusExporter:
{{ toYaml .Values.fluentbit.output.prometheusMetricsExporter.metricsExporter | indent 4}}
{{- end }}
{{- end }}