{{- if .Values.Kubernetes -}}
{{- if .Values.fluentd.enable -}}
apiVersion: fluentd.fluent.io/v1alpha1
kind: Fluentd
metadata:
  name: {{ .Values.fluentd.name }}
  labels:
    app.kubernetes.io/name: fluentd
spec:
  globalInputs:
    - forward:
        bind: 0.0.0.0
        port: {{ .Values.fluentd.port }}
  replicas: {{ .Values.fluentd.replicas }}
  image: {{ include "fluentbit-operator.image" .Values.fluentd.image }}
  resources:
  {{- toYaml .Values.fluentd.resources | nindent 4  }}
  fluentdCfgSelector:
    matchLabels:
      config.fluentd.fluent.io/enabled: "true"
{{- end }}
{{- end }}
