{{- if .Values.Kubernetes -}}
{{- if .Values.fluentd.enable -}}
apiVersion: fluentd.fluent.io/v1alpha1
kind: Fluentd
metadata:
  name: {{ .Values.fluentd.name }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/name: fluentd
spec:
  globalInputs:
    - forward:
        bind: 0.0.0.0
        port: {{ .Values.fluentd.port }}
  replicas: {{ .Values.fluentd.replicas }}
  image: {{ .Values.fluentd.image.repository }}:{{ .Values.fluentd.image.tag }}
  {{- if .Values.fluentd.imagePullSecrets }}
  imagePullSecrets:
  {{ toYaml .Values.fluentd.imagePullSecrets | indent 4 }}
  {{- end }}
  mode: {{ .Values.fluentd.mode }}
  resources:
  {{- toYaml .Values.fluentd.resources | nindent 4  }}
  fluentdCfgSelector:
    matchLabels:
      config.fluentd.fluent.io/enabled: "true"
  {{- if .Values.fluentd.envVars }}
  envVars:
  {{- toYaml .Values.fluentd.envVars | nindent 4 }}
  {{- end }}
  {{- if .Values.fluentd.securityContext }}
  containerSecurityContext:
  {{ toYaml .Values.fluentd.securityContext | nindent 4 }}
  {{- end }}
  {{- if .Values.fluentd.podSecurityContext }}
  securityContext:
  {{ toYaml .Values.fluentd.podSecurityContext | nindent 4 }}
  {{- end }}
  {{- if .Values.fluentd.schedulerName }}
  schedulerName: {{ .Values.fluentd.schedulerName }}
  {{- end }}
  {{- if .Values.fluentd.logLevel }}
  logLevel: {{ .Values.fluentd.logLevel }}
  {{- end }}
  {{- with .Values.fluentd.priorityClassName }}
  priorityClassName: {{ . }}
  {{- end }}
  {{- if .Values.fluentd.extras }}
  {{ .Values.fluentd.extras | toYaml | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
