livenessProbe:
  httpGet:
    path: /metrics
    port: metrics
  initialDelaySeconds: 5
  periodSeconds: 15
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 12

readinessProbe:
  httpGet:
    path: /metrics
    port: metrics
  initialDelaySeconds: 5
  periodSeconds: 15
  timeoutSeconds: 2
  successThreshold: 1
  failureThreshold: 6
