{{- $ingressApiIsStable := eq (include "fluent-bit.ingress.isStable" .) "true" -}}
{{- $ingressSupportsIngressClassName := eq (include "fluent-bit.ingress.supportsIngressClassName" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "fluent-bit.ingress.supportsPathType" .) "true" -}}
{{- $fullName := include "fluent-bit.fullname" . -}}

{{- if or ( eq .Values.kind "Deployment" ) ( eq .Values.kind "StatefulSet" ) }}
{{- range $i, $v := .Values.ingresses -}}
{{- $svcPort := $v.servicePort -}}
apiVersion: {{ include "fluent-bit.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ (printf "%s-%s" ($fullName | trunc 60) (toString $i)) | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fluent-bit.labels" . | nindent 4 }}
  {{- with $v.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and $ingressSupportsIngressClassName $v.ingressClassName }}
  ingressClassName: {{ $v.ingressClassName }}
  {{- end -}}
  {{- if $v.tls }}
  tls:
  {{- range $v.tls }}
    - hosts:
        {{- toYaml .hosts | nindent 8 }}
      secretName: {{ .secretName }}
  {{- end }}
  {{- end }}
  rules:
    {{- range $v.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ .path }}
            {{- if $ingressSupportsPathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ $fullName }}
                port:
                  {{- if .port }}
                  number: {{ .port }}
                  {{- else }}
                  number: {{ $svcPort }}
                  {{- end }}
              {{- else }}
              serviceName: {{ $fullName }}
              {{- if .port }}
              servicePort: {{ .port }}
              {{- else }}
              servicePort: {{ $svcPort }}
              {{- end }}
              {{- end }}
        {{- end }}
    {{- end }}
{{- end }}
{{- end }}