{{- if .Values.networkPolicy.enabled }}
apiVersion: "networking.k8s.io/v1"
kind: "NetworkPolicy"
metadata:
  name: {{ include "fluent-bit.fullname" . | quote }}
  labels:
    {{- include "fluent-bit.labels" . | nindent 4 }}
spec:
  policyTypes:
    {{- if .Values.networkPolicy.egress.customRules }}
    - "Egress"
    {{- end }}
    - "Ingress"
  podSelector:
    matchLabels:
      {{- include "fluent-bit.selectorLabels" . | nindent 6 }}
  {{- with .Values.networkPolicy.egress.customRules }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ingress:
    - from:
        {{- toYaml .Values.networkPolicy.ingress.from | nindent 8 }}
      ports:
        - protocol: "TCP"
          port: {{ .Values.service.port }}
        {{- if .Values.networkPolicy.ingress.includeExtraPorts }}
          {{- range .Values.extraPorts }}
        - protocol: {{ .protocol | quote }}
          port: {{ .port }}
          {{- end }}
        {{- end}}
    {{- with .Values.networkPolicy.ingress.customRules }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
