{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  labels:
    {{- include "fluent-bit.labels" . | nindent 4 }}
  name: {{ include "fluent-bit.fullname" . }}
spec:
  {{- with .Values.resourceQuota.hard }}
  hard:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  scopeSelector:
    matchExpressions:
      - operator: In
        scopeName: PriorityClass
        values:
          - {{ .Values.priorityClassName }}
{{- end }}
