{{- if and .Values.tenx.enabled .Values.tenx.apiKey (ne .Values.tenx.apiKey "NO-API-KEY") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fluent-bit.fullname" . }}-tenx-api-key
  labels:
    {{- include "fluent-bit.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.tenx.apiKey | b64enc | quote }}
{{- end }}
{{- if and .Values.tenx.enabled .Values.tenx.gitToken }}
{{- if and .Values.tenx.apiKey (ne .Values.tenx.apiKey "NO-API-KEY") }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fluent-bit.fullname" . }}-tenx-git-token
  labels:
    {{- include "fluent-bit.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.tenx.gitToken | b64enc | quote }}
{{- end }}
