apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluent-bit.headlessServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fluent-bit.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    prometheus.io/service-monitor: "false"
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  {{- if (semverCompare ">= 1.31-0" .Capabilities.KubeVersion.Version) }}
  {{- with .Values.service.trafficDistribution }}
    trafficDistribution: {{ . }}
  {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- if .Values.extraPorts }}
    {{- range .Values.extraPorts }}
    - name: {{ .name }}
      targetPort: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
    {{- end }}
  {{- end }}
  selector:
    {{- include "fluent-bit.selectorLabels" . | nindent 4 }}
