apiVersion: v1
kind: Service
metadata:
  name: {{ include "fluent-bit-aggregator.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fluent-bit-aggregator.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if (semverCompare ">= 1.31-0" .Capabilities.KubeVersion.Version) }}
{{- with .Values.service.trafficDistribution }}
  trafficDistribution: {{ . }}
{{- end }}
{{- end }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
  {{- range .Values.service.additionalPorts }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ default "TCP" .protocol }}
  {{- end }}
  selector:
    {{- include "fluent-bit-aggregator.selectorLabels" . | nindent 4 }}
