{{- if and .Values.serviceMonitor.enabled .Values.service.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "fluent-bit-collector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "fluent-bit-collector.labels" . | nindent 4 }}
  {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  jobLabel: app.kubernetes.io/instance
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "fluent-bit-collector.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /api/v2/metrics/prometheus
    {{- with .Values.serviceMonitor.endpointConfig }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- range .Values.serviceMonitor.additionalEndpoints }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
