apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "fluentd.labels" . | nindent 4 }}
  name: fluentd-prometheus-conf-{{ include "fluentd.shortReleaseName" . }}
data:
  prometheus.conf: |-
    <source>
      @type prometheus
      @id in_prometheus
      bind "0.0.0.0"
      port 24231
      metrics_path "/metrics"
    </source>

    <source>
      @type prometheus_monitor
      @id in_prometheus_monitor
    </source>

    <source>
      @type prometheus_output_monitor
      @id in_prometheus_output_monitor
    </source>
